name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - attributed_text
  - doc/website
  - super_clones/bear
  - super_clones/google_docs
  - super_clones/ios_messenger
  - super_clones/medium
  - super_clones/obsidian
  - super_clones/quill
  - super_clones/slack
  - super_editor
  - super_editor_clipboard
  - super_editor_spellcheck
  - super_editor_spellcheck/example
  - super_keyboard
  - super_keyboard/doc/website
  - super_text_layout
  - website

dependency_overrides:
  intl: 0.20.2

  vector_math: ^2.2.0
